spring:
  application:
    name: transaction-service
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/transaction_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

server:
  port: 8082
